//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdgk.GR.UI {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XD100Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XD100Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xdgk.GR.UI.XD100Strings", typeof(XD100Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 修正值(℃) 的本地化字符串。
        /// </summary>
        internal static string AdjustHeaderText {
            get {
                return ResourceManager.GetString("AdjustHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修正值超范围! 的本地化字符串。
        /// </summary>
        internal static string AdjustValueOutOfRange {
            get {
                return ResourceManager.GetString("AdjustValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模拟阀 的本地化字符串。
        /// </summary>
        internal static string AnalogValve {
            get {
                return ResourceManager.GetString("AnalogValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在执行操作, 请稍后再试! 的本地化字符串。
        /// </summary>
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 &apos;{0}&apos; ... 的本地化字符串。
        /// </summary>
        internal static string ExecutingOpera {
            get {
                return ResourceManager.GetString("ExecutingOpera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先读取控制参数! 的本地化字符串。
        /// </summary>
        internal static string FirstReadGRControlParams {
            get {
                return ResourceManager.GetString("FirstReadGRControlParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择供热站点! 的本地化字符串。
        /// </summary>
        internal static string FirstSelectGRDevice {
            get {
                return ResourceManager.GetString("FirstSelectGRDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一条数据! 的本地化字符串。
        /// </summary>
        internal static string FirstSelectItem {
            get {
                return ResourceManager.GetString("FirstSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次供温(℃) 的本地化字符串。
        /// </summary>
        internal static string GT2 {
            get {
                return ResourceManager.GetString("GT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点尚未连接, 请稍后再试! 的本地化字符串。
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的模式 &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string NotSupportMode {
            get {
                return ResourceManager.GetString("NotSupportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室外温度 的本地化字符串。
        /// </summary>
        internal static string OT {
            get {
                return ResourceManager.GetString("OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度控制曲线 的本地化字符串。
        /// </summary>
        internal static string OTGT2ControlLine {
            get {
                return ResourceManager.GetString("OTGT2ControlLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室外温度 的本地化字符串。
        /// </summary>
        internal static string OTHeaderText {
            get {
                return ResourceManager.GetString("OTHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室外温度必须介于 &apos;{0}&apos; 到 &apos;{1}&apos; 之间 的本地化字符串。
        /// </summary>
        internal static string OTMustInMinMax {
            get {
                return ResourceManager.GetString("OTMustInMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待操作 的本地化字符串。
        /// </summary>
        internal static string StateNone {
            get {
                return ResourceManager.GetString("StateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取供温曲线 的本地化字符串。
        /// </summary>
        internal static string StateReadLine {
            get {
                return ResourceManager.GetString("StateReadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取供温模式 的本地化字符串。
        /// </summary>
        internal static string StateReadMode {
            get {
                return ResourceManager.GetString("StateReadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置供温曲线 的本地化字符串。
        /// </summary>
        internal static string StateWriteLine {
            get {
                return ResourceManager.GetString("StateWriteLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置供温模式 的本地化字符串。
        /// </summary>
        internal static string StateWriteMode {
            get {
                return ResourceManager.GetString("StateWriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间(小时) 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分时控制曲线 的本地化字符串。
        /// </summary>
        internal static string TimeControlLine {
            get {
                return ResourceManager.GetString("TimeControlLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间(小时) 的本地化字符串。
        /// </summary>
        internal static string TimeHeaderText {
            get {
                return ResourceManager.GetString("TimeHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三位阀 的本地化字符串。
        /// </summary>
        internal static string TrinityValve {
            get {
                return ResourceManager.GetString("TrinityValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成功 的本地化字符串。
        /// </summary>
        internal static string WriteControlModeSuccess {
            get {
                return ResourceManager.GetString("WriteControlModeSuccess", resourceCulture);
            }
        }
    }
}
