//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3 {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C3.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 转换 的本地化字符串。
        /// </summary>
        internal static string BytesConverter {
            get {
                return ResourceManager.GetString("BytesConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备(&amp;A)... 的本地化字符串。
        /// </summary>
        internal static string ContextMenuAddDevice {
            get {
                return ResourceManager.GetString("ContextMenuAddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验 的本地化字符串。
        /// </summary>
        internal static string Crcer {
            get {
                return ResourceManager.GetString("Crcer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        internal static string DeviceAddinName {
            get {
                return ResourceManager.GetString("DeviceAddinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型 的本地化字符串。
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听 的本地化字符串。
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择设备 的本地化字符串。
        /// </summary>
        internal static string SelectDeviceFirst {
            get {
                return ResourceManager.GetString("SelectDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择站点 的本地化字符串。
        /// </summary>
        internal static string SelectStationFirst {
            get {
                return ResourceManager.GetString("SelectStationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点 的本地化字符串。
        /// </summary>
        internal static string StationAddinName {
            get {
                return ResourceManager.GetString("StationAddinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点类型 的本地化字符串。
        /// </summary>
        internal static string StationType {
            get {
                return ResourceManager.GetString("StationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除吗? 的本地化字符串。
        /// </summary>
        internal static string SureToDelete {
            get {
                return ResourceManager.GetString("SureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出吗? 的本地化字符串。
        /// </summary>
        internal static string SureToQuit {
            get {
                return ResourceManager.GetString("SureToQuit", resourceCulture);
            }
        }
    }
}
