//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xdgk.GR.Common{
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XD100ModbusStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XD100ModbusStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xdgk.GR.Common.XD100ModbusStrings", typeof(XD100ModbusStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 温度曲线+二次回温 的本地化字符串。
        /// </summary>
        internal static string LineAndBT2 {
            get {
                return ResourceManager.GetString("LineAndBT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度曲线+二次温差 的本地化字符串。
        /// </summary>
        internal static string LineAndDiffT2 {
            get {
                return ResourceManager.GetString("LineAndDiffT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度曲线+二次供温 的本地化字符串。
        /// </summary>
        internal static string LineAndGT2 {
            get {
                return ResourceManager.GetString("LineAndGT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持模式 &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string NotSupportMode {
            get {
                return ResourceManager.GetString("NotSupportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度设定+二次回温 的本地化字符串。
        /// </summary>
        internal static string SettingAndBT2 {
            get {
                return ResourceManager.GetString("SettingAndBT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度设定+二次温差 的本地化字符串。
        /// </summary>
        internal static string SettingAndDiffT2 {
            get {
                return ResourceManager.GetString("SettingAndDiffT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度设定+二次供温 的本地化字符串。
        /// </summary>
        internal static string SettingAndGT2 {
            get {
                return ResourceManager.GetString("SettingAndGT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调节阀开度设定 的本地化字符串。
        /// </summary>
        internal static string ValveOpenDegree {
            get {
                return ResourceManager.GetString("ValveOpenDegree", resourceCulture);
            }
        }
    }
}
